<input type="button" class="selection" onClick="invertAllinSection(this.parentNode);" value="inverser"></input>
<input type="button" class="selection" onClick="doSimpleinSection(this.parentNode,true);" value="tout"></input>
<input type="button" class="selection" onClick="doSimpleinSection(this.parentNode,false);" value="aucun"></input>
<input type="button" class="selection" onClick="doinSection(this.parentNode,'type_fichier','.jpg',true);" value="images"></input>
